### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Slashgear** [PolytechLyon/isi3-tp2-visiteur-pittore-tp2#1]
- Pouvez vous m'expliquer le cas d'utilisation du pattern visiteur ?

- On range les choses en packages (:warning:  les packages en java c'est en minuscule)

- le rapport c'est bien 👍 

- La priorité c'est sympa mais on évite les magic numbers
https://github.com/PolytechLyon/isi3-tp2-visiteur-pittore-tp2/blob/4e6dae70ffeba123d66c690a37cf28f8930f131a/src/main/java/Addition.java#L13-L15

On préfèrera retourner un ENUM valué qui donnera un nom à cette priorité. Vous comprenez pourquoi ?

**Comment by axbator28** [comment]
* Le design pattern visiteur permet de faire des opérations sur plusieurs objets, sans que l'on ai besoin d'en modifier le code.. Dans notre cas, cela permet "d'extérioriser" le parcours d'expression (qui est un graphe au final) et le calcul de sa valeur. De plus, si on voulait ajouter un nouveau traitement, on ajouterait juste un nouveau Visiteur, sans rien modifier d'autre (car les objets acceptent pour le moment toute sorte de visiteur)

* J'ai créé le package visiteur et tout mis dedans.

* L'ENUM Priorite est mis en place. C'est pratique car toutes les priorités sont regroupées, on peut aussi en rajouter ou modifier une facilement, il y a une méthode commune pour en appeler la valeur, qui ne sort donc plus du chapeau.

```java
package visiteur;

public enum Priorite {
    ADDITION(2), CONSTANTE(4), MULTIPLICATION(3), NEGATION(1);
    private int value;

    private Priorite(int value) { this.value = value; }

    public int getValue(){ return value;};

}
```

La fonction getPriorite() de l'addition :
```java
	public int getPriorite() {
		return Priorite.ADDITION.getValue();
	}
```

**Comment by Slashgear** [comment]
👌
